const app = document.querySelector('#app');
let token = localStorage.takeoffToken || '', state = { step: 1, personal:{}, identity:{}, vehicle:{}, documents:{}, status:'In progress' };
const steps = ['Personal details','Identity check','Vehicle','Documents','Review'];
const request = async (url, options={}) => { const r=await fetch(url,{headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...options}); const raw=await r.text(); let d; try{d=JSON.parse(raw)}catch{throw Error('The server returned an invalid response. Please refresh and try again.');} if(!r.ok){const e=Error(d.error||'Request failed. Please try again.');Object.assign(e,d);throw e;} return d; };
const esc = s => String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function layout(content){app.innerHTML=`<div class="shell"><div class="top"><div class="brand">take<i>OFF</i></div>${token?'<button class="link" onclick="profiles()">Reviewer demo</button><button class="link" onclick="signout()">Sign out</button>':''}</div>${content}</div>`}
function auth(mode='signup'){layout(`<section class="card auth"><div class="eyebrow">Courier partner portal</div><h1>${mode==='signup'?'Start delivering with TakeOFF':'Welcome back'}</h1><p>${mode==='signup'?'Apply to deliver packages on your own schedule. It takes around 10 minutes.':'View your existing driver application.'}</p><form id="authForm">${mode==='signup'?'<div class="field"><label>Full name</label><input required name="name" placeholder="Jamie Moyo"></div>':''}<div class="field"><label>Email address</label><input required type="email" name="email" placeholder="jamie@example.test"></div><div class="field"><label>Mobile number</label><input ${mode==='signup'?'required':''} name="phone" placeholder="+263 77 123 4567"></div><div id="formError"></div><button class="btn lime" style="width:100%">${mode==='signup'?'Send verification code':'View application status'}</button></form><p style="text-align:center;margin-top:22px">${mode==='signup'?'Already applied? <button class="link" onclick="auth(\'signin\')">Check your application status</button>':'New to TakeOFF? <button class="link" onclick="auth()">Start an application</button>'}</p></section>`);document.querySelector('#authForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));try{if(mode==='signin'){const x=await request('/api/auth/signin',{method:'POST',body:JSON.stringify({identifier:v.email})});loggedIn(x,true)}else{const x=await request('/api/auth/request-otp',{method:'POST',body:JSON.stringify(v)});verify(v,x)} }catch(x){if(x.registered) existingApplicant(x.identifier,x.status); else error(x.message)}}}
function verify(v,x){layout(`<section class="card auth"><div class="eyebrow">One last step</div><h1>Check your inbox</h1><p>We sent a six-digit verification code to <b>${esc(v.email)}</b>. It expires in 10 minutes.</p><form id="verifyForm"><div class="field"><label>Verification code</label><input required inputmode="numeric" pattern="[0-9]{6}" maxlength="6" name="code" placeholder="000000" autocomplete="one-time-code"></div><div id="formError"></div><button class="btn lime" style="width:100%">Verify and continue</button></form></section>`);document.querySelector('#verifyForm').onsubmit=async e=>{e.preventDefault();try{const z=await request('/api/auth/verify-otp',{method:'POST',body:JSON.stringify({...v,challengeId:x.challengeId,code:new FormData(e.target).get('code')})});loggedIn(z)}catch(e){if(e.registered)existingApplicant(e.identifier,e.status);else error(e.message)}}}
async function loggedIn(x, showStatus=false){token=x.token;localStorage.takeoffToken=token;const data=await request('/api/application');if(data.application)state=data.application;if(showStatus && data.application)return applicationStatus(data.application);renderStep()}
function existingApplicant(identifier,status){layout(`<section class="card auth"><div class="icon">✓</div><div class="eyebrow">Application found</div><h1>You’re already in our system.</h1><p>We found an application linked to these details. Its current status is <span class="tag">${esc(status)}</span>.</p><button class="btn lime" style="width:100%" onclick="viewExistingStatus('${esc(identifier)}')">View application status</button><p style="text-align:center;margin-top:22px"><button class="link" onclick="auth()">Use different details</button></p></section>`)}
async function viewExistingStatus(identifier){try{const x=await request('/api/auth/signin',{method:'POST',body:JSON.stringify({identifier})});loggedIn(x,true)}catch(e){auth('signin');error(e.message)}}
function applicationStatus(application){const name=application.personal?.fullName || 'there', status=application.status || 'In progress';layout(`<section class="card complete"><div class="icon">${status==='Submitted'?'✓':'…'}</div><div class="eyebrow">Driver application</div><h1>${status==='Submitted'?'Your application is under review.':'Your application is in progress.'}</h1><p>Hi ${esc(name)}. Current status: <span class="tag">${esc(status)}</span></p>${status==='Submitted'?'<p>Our operations team will notify you once a decision has been made.</p>':'<p>You can return to your saved application and complete the remaining details.</p><button class="btn lime" onclick="renderStep()">Continue application</button>'}<p style="margin-top:28px"><button class="link" onclick="signout()">Sign out</button></p></section>`)}
function applicationStatus(application){const name=application.personal?.fullName || 'there',status=application.status||'In progress';const copy={Submitted:['✓','Your application is under review.','Our operations team will notify you once a decision has been made.'],Approved:['✓','You’re approved to deliver.','Your test driver application has been approved.'],['Changes requested']:['↺','We need an update from you.','Please return to your application and correct the requested details.']}[status]||['…','Your application is in progress.','You can return to your saved application and complete the remaining details.'];layout(`<section class="card complete"><div class="icon">${copy[0]}</div><div class="eyebrow">Driver application</div><h1>${copy[1]}</h1><p>Hi ${esc(name)}. Current status: <span class="tag">${esc(status)}</span></p><p>${copy[2]}</p>${status==='In progress'||status==='Changes requested'?'<button class="btn lime" onclick="renderStep()">Continue application</button>':''}<p style="margin-top:28px"><button class="link" onclick="signout()">Sign out</button></p></section>`)}
function error(t){document.querySelector('#formError').innerHTML=`<div class="error">${esc(t)}</div>`}
function progress(){return `<div class="step-label"><span>Step ${state.step} of 5</span><span>${steps[state.step-1]}</span></div><div class="progress">${steps.map((_,i)=>`<span class="${i<state.step?'active':''}"></span>`).join('')}</div>`}
const today = () => new Date().toISOString().slice(0,10);
const input=(key,label,type='text',placeholder='',attrs='')=>`<div class="field"><label>${label}</label><input type="${type}" required name="${key}" value="${esc(state.personal[key]||state.identity[key]||state.vehicle[key]||'')}" placeholder="${placeholder}" ${attrs}></div>`;
function renderStep(){let content=''; if(state.step===1) content=`<h2>Tell us about yourself</h2><p>Use test information only for this demo application.</p><form id="stepForm"><div class="grid">${input('fullName','Legal name','text','Jamie Moyo')}${input('dateOfBirth','Date of birth','date','',`max="${today()}"`)}${input('email','Email address','email','jamie@example.test')}${input('phone','Mobile number','tel','+263 77 123 4567')}<div class="field"><label>Home address</label><input required name="address" value="${esc(state.personal.address)}" placeholder="12 Demo Street, Harare"></div><div class="field"><label>City / service area</label><input required name="city" value="${esc(state.personal.city)}" placeholder="Harare"></div></div>${buttons()}</form>`;
else if(state.step===2)content=`<h2>Verify your identity</h2><p>We use this information to confirm you can provide delivery services.</p><form id="stepForm"><div class="grid"><div class="field"><label>Identity document type</label><select required name="idType"><option value="">Select document</option>${['National ID (test)','Passport (test)','Driver licence (test)'].map(x=>`<option ${state.identity.idType===x?'selected':''}>${x}</option>`).join('')}</select></div>${input('idNumber','Test identity number','text','DEMO-123456')}${input('licenceNumber','Driver licence number','text','DL-TEST-00981')}<div class="field"><label>Licence expiry date</label><input required type="date" min="${today()}" name="licenceExpiry" value="${esc(state.identity.licenceExpiry)}"><small>Your licence must still be valid today.</small></div></div>${buttons()}</form>`;
else if(state.step===3)content=`<h2>Your delivery vehicle</h2><p>Tell us about the vehicle you will use for deliveries.</p><form id="stepForm"><div class="grid">${input('vehicleType','Vehicle type','text','Motorbike')}${input('makeModel','Make and model','text','Honda CB125F')}${input('plate','Registration plate','text','TEST 1234')}${input('year','Year of manufacture','number','2024',`min="1900" max="${new Date().getFullYear()+1}"`)}<div class="field"><label>Vehicle colour</label><input required name="colour" value="${esc(state.vehicle.colour)}" placeholder="Red"></div><div class="field"><label>Insurance expiry date</label><input required type="date" min="${today()}" name="insuranceExpiry" value="${esc(state.vehicle.insuranceExpiry)}"><small>Your insurance must still be valid today.</small></div></div>${buttons()}</form>`;
else if(state.step===4)content=`<h2>Upload required documents</h2><p>Use sample or test files only. Files are retained with your demo profile.</p><form id="stepForm"><div class="doc"><div><b>Driver licence</b><small>Photo, PDF, PNG or JPG</small></div><input required type="file" data-doc="licence" accept="image/*,.pdf"></div><div class="doc"><div><b>Identity document</b><small>Photo, PDF, PNG or JPG</small></div><input required type="file" data-doc="identity" accept="image/*,.pdf"></div><div class="doc"><div><b>Vehicle registration</b><small>Photo, PDF, PNG or JPG</small></div><input required type="file" data-doc="registration" accept="image/*,.pdf"></div><div class="doc"><div><b>Insurance certificate</b><small>Photo, PDF, PNG or JPG</small></div><input required type="file" data-doc="insurance" accept="image/*,.pdf"></div><div class="notice">For this prototype, files up to 1 MB are saved with the test profile.</div>${buttons()}</form>`;
else content=review();layout(`<section class="card">${progress()}${content}</section>`); if(state.step<5) bindStep();}
function buttons(){return `<div class="actions">${state.step>1?'<button type="button" class="btn secondary" onclick="back()">Back</button>':''}<button class="btn lime">Continue</button></div>`}
function validateStep(data){
  const date = value => { const [year,month,day]=String(value).split('-').map(Number); return new Date(year,month-1,day); };
  const isDate = value => { if(!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false; const [year,month,day]=value.split('-').map(Number), d=date(value); return d.getFullYear()===year && d.getMonth()===month-1 && d.getDate()===day; };
  if(state.step===1){ if(!isDate(data.dateOfBirth)) throw Error('Enter a valid date of birth.'); const age=(Date.now()-date(data.dateOfBirth))/31557600000; if(age<18) throw Error('Drivers must be at least 18 years old.'); if(age>100) throw Error('Please enter a realistic date of birth.'); }
  if(state.step===2 && (!isDate(data.licenceExpiry)||data.licenceExpiry<today())) throw Error('Your licence expiry date must be today or later.');
  if(state.step===3){ if(!/^\d{4}$/.test(data.year)||Number(data.year)<1900||Number(data.year)>new Date().getFullYear()+1) throw Error(`Enter a vehicle year from 1900 to ${new Date().getFullYear()+1}.`); if(!isDate(data.insuranceExpiry)||data.insuranceExpiry<today()) throw Error('Your insurance expiry date must be today or later.'); }
}
function bindStep(){document.querySelector('#stepForm').onsubmit=async e=>{e.preventDefault();try{if(!e.target.reportValidity())return;if(state.step===4){const files=[...document.querySelectorAll('[data-doc]')];for(const el of files){const f=el.files[0];if(!f)throw Error('Please add all four documents.');if(f.size>1024*1024)throw Error('Use files smaller than 1 MB in this prototype.');state.documents[el.dataset.doc]={name:f.name,type:f.type,size:f.size,data:await readFile(f)};}}else{const data=Object.fromEntries(new FormData(e.target));validateStep(data);Object.assign(state[state.step===1?'personal':state.step===2?'identity':'vehicle'],data)}state.step++;await save();renderStep()}catch(x){error(x.message)}}}
function readFile(f){return new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)})}
function review(){const p=state.personal,i=state.identity,v=state.vehicle;return `<h2>Review your application</h2><p>Confirm your test details before submitting.</p><div class="review"><strong>Personal & contact</strong>${esc(p.fullName)} · ${esc(p.email)} · ${esc(p.phone)}<br>${esc(p.address)}, ${esc(p.city)}</div><div class="review"><strong>Identity & licence</strong>${esc(i.idType)} ${esc(i.idNumber)} · Licence ${esc(i.licenceNumber)}</div><div class="review"><strong>Vehicle</strong>${esc(v.vehicleType)} · ${esc(v.makeModel)} · ${esc(v.plate)}</div><div class="review"><strong>Documents captured</strong>${Object.values(state.documents).map(d=>esc(d.name)).join(', ')}</div><div class="actions"><button class="btn secondary" onclick="back()">Back</button><button class="btn lime" onclick="submitApplication()">Submit application</button></div>`}
async function save(){state.status='In progress';await request('/api/application',{method:'POST',body:JSON.stringify(state)})}async function submitApplication(){state.status='Submitted';await request('/api/application',{method:'POST',body:JSON.stringify(state)});layout(`<section class="card complete"><div class="icon">✓</div><div class="eyebrow">Application submitted</div><h1>You're cleared for review.</h1><p>Thanks, ${esc(state.personal.fullName)}. Our operations team will review your driver and vehicle details. We’ll notify you at ${esc(state.personal.email)} once a decision has been made.</p><span class="tag">Under review</span><p style="margin-top:28px"><button class="link" onclick="profiles()">View saved test profiles</button></p></section>`)}function back(){state.step--;renderStep()}function signout(){localStorage.removeItem('takeoffToken');token='';state={step:1,personal:{},identity:{},vehicle:{},documents:{},status:'In progress'};auth()}async function profiles(){try{const x=await request('/api/admin/profiles');layout(`<section class="card"><div class="eyebrow">Demo admin view</div><h1>Saved test driver profiles</h1><p>These profiles and document metadata are persisted by the backend.</p><div class="profiles">${x.profiles.length?x.profiles.map(q=>`<div class="profile"><b>${esc(q.personal.fullName)}</b><span class="tag">${esc(q.status)}</span><p>${esc(q.personal.email)} · ${esc(q.vehicle.makeModel)} (${esc(q.vehicle.plate)})<br>Documents: ${Object.values(q.documents||{}).map(d=>esc(d.name)).join(', ')}</p></div>`).join(''):'No profiles yet.'}</div></section>`)}catch(e){auth()}}
async function submitApplication(){state.status='Submitted';await request('/api/application',{method:'POST',body:JSON.stringify(state)});applicationStatus(state)}
async function profiles(){try{const x=await request('/api/admin/profiles');layout(`<section class="card"><div class="eyebrow">Demo reviewer view</div><h1>Saved test driver profiles</h1><p>Review captured test details and documents, then update the driver's application status.</p><div class="profiles">${x.profiles.length?x.profiles.map(q=>`<div class="profile"><b>${esc(q.personal.fullName)}</b><span class="tag">${esc(q.status)}</span><p><b>Contact</b> ${esc(q.personal.email)} · ${esc(q.personal.phone)}<br><b>Identity</b> ${esc(q.identity.idType)} · ${esc(q.identity.idNumber)} · licence expires ${esc(q.identity.licenceExpiry)}<br><b>Vehicle</b> ${esc(q.vehicle.makeModel)} (${esc(q.vehicle.plate)}) · insurance expires ${esc(q.vehicle.insuranceExpiry)}<br><b>Documents</b> ${Object.values(q.documents||{}).map(d=>`${esc(d.name)} (${Math.ceil(d.size/1024)} KB)`).join(', ') || 'None'}</p>${q.status==='Submitted'?`<div class="actions"><button class="btn secondary" onclick="updateProfileStatus('${q.id}','Changes requested')">Request changes</button><button class="btn lime" onclick="updateProfileStatus('${q.id}','Approved')">Approve application</button></div>`:''}</div>`).join(''):'No profiles yet.'}</div></section>`)}catch(e){auth()}}
async function updateProfileStatus(id,status){try{await request(`/api/admin/profiles/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});await profiles()}catch(e){error(e.message)}}
token?request('/api/application').then(x=>{if(x.application)state=x.application;x.application?.status==='Submitted'||x.application?.status==='Approved'?applicationStatus(state):renderStep()}).catch(()=>auth()):auth();
